### ISSUE TITLE
client-side sliding collision?

### ISSUE THREAD

**Issue by Thundros** [tehzwen/MultiplayerWebGL#4]
@tehzwen Can  you add client-side sliding collision when player is up against wall? & if player hits head on platform, there is sliding collision as well?

i would absolutely LOVE  to beta test this for you!

thank you!

**Comment by Thundros** [comment]
@tehzwen hello?

**Comment by tehzwen** [comment]
Sorry for the late response. 

While there is some (emphasis on the some) collision detection logic in the game right now, this is something I plan on improving in the future. 

Also thanks for letting me know!

**Comment by Thundros** [comment]
@tehzwen Can you add some simple sliding collision when up against walls, hitting head on bottom of block, and when on platforms? I will ABSOLUTELY beta test this for you!

Thank you!

**Comment by tehzwen** [comment]
Yup, as mentioned above I plan on adding more collision detection

**Comment by Thundros** [comment]
Awesome! Thank you SO much! When do you expect to have a test demo ready & I'll test it for ya?

**Comment by tehzwen** [comment]
As this is a side project, I'm honestly not sure when a "demo" type thing would be available. It's always available to be cloned and tried out even in its current state however

**Comment by tehzwen** [comment]
Collision detection has been improved to allow detection from any side and accurately move away from the collided object. Will close this issue in the next couple days unless another issue is found with it.

**Comment by Thundros** [comment]
@tehzwen Would like to try this, but can you use regular MySQLi for this? I have a Xampp server I would like to test this on.

**Comment by tehzwen** [comment]
It should work with a different type of database but you may have to make some changes to the program to interface correctly with it. I Can create a file with the queries to create the database that are run in postgres and you could always replicate them in MySQLi if that helps.

**Comment by Thundros** [comment]
@tehzwen Yea I just need a simple way of connecting to MySQLi so I can beta test the client. :)

**Comment by tehzwen** [comment]
Yep I pushed an SQL file with the commands I used in postgres to make my database. If you can alter them for yours (may need to alter some of the queries in server.js) then the client should work

**Comment by Thundros** [comment]
@tehzwen I'm fine with Altering the SQL file, but I don't know node that much to change what to what to get it to work. :( I REALLY want to try this demo.

**Comment by tehzwen** [comment]
If you click on my profile and send me an email I can provide better help to get it working for you or host it locally and have you try it out.

**Comment by Thundros** [comment]
@tehzwen Email sent :)

**Comment by Thundros** [comment]
@tehzwen Email sent again :)

**Comment by Thundros** [comment]
@tehzwen : Just wanted to let you know I sent you a google drive link to the full project. You can read the email for more details. :) The SQL file is both in sqlbackups & in the last email as well. :) Just wanted to give you a heads up! :)

**Comment by unityblows** [comment]
what an AMAZINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG WEBGL GAME wOw
